.github/workflows/ci.yml

fix: ci on pr

---

.github/workflows/ci.yml
src/main/java/app/coronawarn/verification/service/TanService.java
src/test/java/app/coronawarn/verification/service/TanServiceTest.java

document reflects reality changes.

Update on OTC subscription/namespace structure

---

DockerfilePaaS
pom.xml

fix: spring repackage

---

src/main/java/app/coronawarn/verification/repository/VerificationAppSessionRepository.java
src/main/java/app/coronawarn/verification/service/AppSessionService.java
src/main/java/app/coronawarn/verification/service/TanService.java

If you want to exclude certain properties from the query result, use projections or query graphs

fix: the usage of JPA findOne

---

README.md

Trivial fix of broken maven website links.

fix: broken maven website links

---

.github/workflows/ci.yml

Let's label the packages with mvn version (without SNAPSHOT) and git short sha - on master build.

feat: mvn version sha

---

docs/architecture-overview.md

Fix latest typos described in #126

Fix typos in architecture overview

---

README.md

Fix: Readme.md

---

pom.xml

lift version due to the fact, that several features made it in this release, not only bug fixes.

chore: version lift 1.1.0

---

pom.xml

temporary deactivate response padding from responses.

chore: lift vers. for temp. resp_padding fix

---

src/main/java/app/coronawarn/verification/controller/ExternalTanController.java
src/main/java/app/coronawarn/verification/controller/ExternalTestStateController.java
src/main/java/app/coronawarn/verification/controller/ExternalTokenController.java
src/main/java/app/coronawarn/verification/model/RegistrationToken.java
src/main/java/app/coronawarn/verification/model/Tan.java
src/main/java/app/coronawarn/verification/model/TestResult.java
src/main/java/app/coronawarn/verification/service/AppSessionService.java
src/test/java/app/coronawarn/verification/VerificationApplicationExternalTest.java
src/test/java/app/coronawarn/verification/VerificationApplicationInternalTest.java

Changed Responsepadding to only apply if fake header exists

---

src/main/java/app/coronawarn/verification/model/RegistrationToken.java
src/main/java/app/coronawarn/verification/model/Tan.java
src/main/java/app/coronawarn/verification/model/TestResult.java

fix: added json ignore if null

---

.grenrc.js

added chore and others to not be included in release notes

chore: update grenrc

---

src/main/java/app/coronawarn/verification/controller/ExternalTokenController.java
src/main/java/app/coronawarn/verification/service/AppSessionService.java

bug: remove additional logging after verification server split #207

fix: remove additional logging

---

.github/workflows/ci-master.yml
src/main/resources/application-external.yml
src/main/resources/application-internal.yml
src/main/resources/application.yml

fix: restrict TLS versions for internal and external connections

---

src/main/java/app/coronawarn/verification/controller/ExternalTestStateController.java

The title says it all.
Thanks for any review and of course for the app itself.

Fix a typo in log message

---

src/main/java/app/coronawarn/verification/controller/ExternalTestStateController.java
src/main/java/app/coronawarn/verification/model/TestResult.java
src/test/java/app/coronawarn/verification/VerificationApplicationExternalTest.java

Fixed Sample Collection naming

fix/Sample Collection naming

---

src/main/java/app/coronawarn/verification/service/AppSessionService.java
src/main/resources/db/changelog.yml
src/main/resources/db/changelog/v003-add-unique-hashed-guid.yml
src/test/java/app/coronawarn/verification/service/EntitiesCleanupServiceTest.java

Fix: Add Unique Constraint to HashedGuid Property

---

src/main/java/app/coronawarn/verification/config/LocalSecurityConfig.java
src/main/java/app/coronawarn/verification/config/MtlsSecurityConfig.java
src/main/java/app/coronawarn/verification/config/VerificationApplicationConfig.java
src/main/resources/application-cloud.yml
src/main/resources/application.yml

* Add Allow-List-Check for mTLS Authentication
* Add Allow-List-Check for mTLS Authentication
* Change Allow-List to Comma seperated

Feat: Allow-List for Certificate Hashes 

---

pom.xml
src/main/java/app/coronawarn/verification/config/VerificationApplicationConfig.java
src/main/java/app/coronawarn/verification/repository/VerificationAppSessionRepository.java
src/main/java/app/coronawarn/verification/repository/VerificationTanRepository.java
src/main/java/app/coronawarn/verification/service/EntitiesCleanupService.java
src/main/resources/application.yml
src/main/resources/db/changelog.yml
src/main/resources/db/changelog/v005-add-shedlock.yml
src/main/resources/db/changelog/v006-add-index-dob-hashed-guid.yml
src/test/java/app/coronawarn/verification/service/EntitiesCleanupServiceTest.java

Moved Delete to DB
Changed Job to Cron
Added index

Feat/Add Shedlock

---

pom.xml

Fix/Bump Log4j to 2.16

---

pom.xml

- spring boot 2.6.6
- h2 2.1.210

fix: bump spring boot 2.6.6

---

pom.xml

Chore: Update Commons-Io
